CREATE DATABASE [MANUFACTURER];

USE [MANUFACTURER];

CREATE TABLE [SUPPLIER](
	[SUPP_ID] INT NOT NULL,
	[SUPP_NAME] VARCHAR(50) NULL,
	[SUPP_LOCATION] VARCHAR(50) NULL,
	[SUPP_COUNTRY] VARCHAR(50) NULL,
	[IS_ACTIVE] BIT NULL,
	PRIMARY KEY (SUPP_ID));


CREATE TABLE [COMPONENT](
	[COMP_ID] INT NOT NULL,
	[COMP_NAME] VARCHAR(50) NULL,
	[DESCRIPTION] VARCHAR(50) NULL,
	[QUANTITY_COMP] INT NULL,
	PRIMARY KEY (COMP_ID));


CREATE TABLE [PRODUCT](
	[PROD_ID] INT NOT NULL,
	[PROD_NAME] VARCHAR(50) NULL,
	[QUANTITY] INT NULL
	PRIMARY KEY (PROD_ID));


CREATE TABLE [PROD_COMP](
	[PROD_ID] INT NOT NULL,
	[COMP_ID] INT NOT NULL,
	[QUANTITY_COMP] INT NULL,
	PRIMARY KEY (PROD_ID, COMP_ID),
	FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (PROD_ID),
	FOREIGN KEY (COMP_ID) REFERENCES COMPONENT (COMP_ID));


CREATE TABLE [COMP_SUPP](
	[SUPP_ID] INT NOT NULL,
	[COMP_ID] INT NOT NULL,
	[ORDER_DATE] DATE NULL,
	[QUANTITY] INT NULL,
	PRIMARY KEY (COMP_ID, SUPP_ID),
	FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIER (SUPP_ID),
	FOREIGN KEY (COMP_ID) REFERENCES COMPONENT (COMP_ID));
